name: Beat Rooster
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3207885
title: Proovin teenust
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E1E0DF'
    - '#6E6F77'
    - '#17171E'
    - '#00FF01'
    - '#0101B4'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
