layout_spectrum: 1
color:
  saturation: 1
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#E1E0DF'
    - '#6E6F77'
    - '#17171E'
    - '#00FF01'
    - '#0101B4'
  rhythmicContrast: 1
typography_spectrum: 0.3207885
name: Beat Rooster
